<?php

use Illuminate\Database\Seeder;

class ListTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	DB::table('_list')->insert([
    		['id'   => 94,  'list_name' =>  'retailer_type',    'item_name' => 'Department Store', 'status' => 1],
    		['id'   => 95,  'list_name' =>  'retailer_type',    'item_name' => 'General Store', 'status' => 1],
    		['id'   => 96,  'list_name' =>  'retailer_type',    'item_name' => 'Kids', 'status' => 1],
    		['id'   => 97,  'list_name' =>  'retailer_type',    'item_name' => 'Fashion', 'status' => 1],
    		['id'   => 98,  'list_name' =>  'retailer_type',    'item_name' => 'Grocery Store', 'status' => 1],
    		['id'   => 110, 'list_name' =>  'state',            'item_name' =>  'AA', 'status' => 1],
    		['id'   => 111, 'list_name' =>  'state',            'item_name' =>  'AK', 'status' => 1],
    		['id'   => 112, 'list_name' =>  'state',            'item_name' =>  'AL',   'status' => 1],
    		['id'   => 113, 'list_name' =>  'state',            'item_name' =>  'AP', 'status' => 1],
    		['id'   => 114, 'list_name' =>  'state',            'item_name' =>  'AR', 'status' => 1],
    		['id'   => 115, 'list_name' =>  'state',            'item_name' =>  'AZ', 'status' => 1],
    		['id'   => 145, 'list_name' =>  'rep_highest_edu_level', 'item_name' => 'High School', 'status' => 1],
    		['id'   => 146, 'list_name' =>  'rep_highest_edu_level', 'item_name' => 'Part Time College', 'status' => 1],
    		['id'   => 147, 'list_name' =>  'rep_highest_edu_level', 'item_name' => 'College', 'status' => 1],
    		['id'   => 148, 'list_name' =>  'rep_highest_edu_level', 'item_name' => 'Post Graduate', 'status' => 1],
    		['id'   => 149, 'list_name' =>  'rep_internet_browser', 'Internet Explorer', 'status' => 1],
    		['id'   => 150, 'list_name' =>  'rep_distance_willing_to_travel', 'item_name' => '25', 'status' => 1],
    		['id'   => 156, 'list_name' =>  'rep_distance_willing_to_travel', 'item_name' => '50', 'status' => 1],
    		['id'   => 157, 'list_name' =>  'rep_distance_willing_to_travel', 'item_name' => '100', 'status' => 1],
    		['id'   => 158, 'list_name' =>  'rep_distance_willing_to_travel', 'item_name' => '150', 'status' => 1],
    		['id'   => 159, 'list_name' =>  'rep_distance_willing_to_travel', 'item_name' => '200+', 'status' => 1],
    		['id'   => 164, 'list_name' =>  'rep_internet_browser', 'item_name' => 'Internet Explorer 3.x', 'status' => 1],
    		['id'   => 165, 'list_name' =>  'rep_internet_browser', 'item_name' => 'Internet Explorer 4.x', 'status' => 1],
    		['id'   => 166, 'list_name' =>  'rep_internet_browser', 'item_name' => 'Internet Explorer 5.x', 'status' => 1],
    		['id'   => 167, 'list_name' =>  'rep_internet_browser', 'item_name' => 'Internet Explorer 6+', 'status' => 1],
    		['id'   => 168, 'list_name' =>  'rep_internet_browser', 'item_name' => 'Netscape Navigator', 'status' => 1],
    		['id'   => 169, 'list_name' =>  'rep_internet_browser', 'item_name' => 'Netscape Navigator 3.x', 'status' => 1],
    		['id'   => 170, 'list_name' =>  'rep_internet_browser', 'item_name' => 'Netscape Navigator 4.x', 'status' => 1],
    		['id'   => 171, 'list_name' =>  'rep_internet_browser', 'item_name' => 'Netscape Navigator 5.x', 'status' => 1],
    		['id'   => 172, 'list_name' =>  'rep_internet_browser', 'item_name' => 'Netscape Navigator 6.x', 'status' => 1],
    		['id'   => 173, 'list_name' =>  'rep_internet_browser', 'item_name' => 'Netscape Navigator 7+', 'status' => 1],
    		['id'   => 174, 'list_name' =>  'rep_internet_browser', 'item_name' => 'America Online', 'status' => 1],
    		['id'   => 175, 'list_name' =>  'rep_internet_browser', 'item_name' => 'America Online 3', 'status' => 1],
    		['id'   => 176, 'list_name' =>  'rep_internet_browser', 'item_name' => 'America Online 4', 'status' => 1],
    		['id'   => 177, 'list_name' =>  'rep_internet_browser', 'item_name' => 'America Online 5+', 'status' => 1],
    		['id'   => 178, 'list_name' =>  'rep_internet_browser', 'item_name' => 'Macintosh versions of the above', 'status' => 1],
    		['id'   => 179, 'list_name' =>  'rep_internet_browser', 'item_name' => 'Opera', 'status' => 1],
    		['id'   => 180, 'list_name' =>  'rep_internet_browser',  'item_name' =>'Other', 'status' => 1],
    		['id'   => 201, 'list_name' =>  'project_types', 'item_name' => 'Merchandising - Special Project', 'status' => 1],
    		['id'   => 202, 'list_name' =>  'project_types', 'item_name' => 'Merchandising - Reset', 'status' => 1],
    		['id'   => 203, 'list_name' =>  'project_types', 'item_name' => 'Merchandising - Product Cut-in', 'status' => 1],
    		['id'   => 204, 'list_name' =>  'project_types', 'item_name' => 'Merchandising - New Store Setup', 'status' => 1],
    		['id'   => 205, 'list_name' =>  'project_types', 'item_name' => 'Merchandising - Display Setup', 'status' => 1],
    		['id'   => 206, 'list_name' =>  'project_types', 'item_name' => 'Merchandising - Continuity/Product Re-order', 'status' => 1],
    		['id'   => 207, 'list_name' =>  'project_types', 'item_name' => 'Demo/Event - Product Sampling', 'status' => 1],
    		['id'   => 208, 'list_name' =>  'project_types', 'item_name' => 'Mystery Shopping - In-Person Mystery Shopping', 'status' => 1],
    		['id'   => 209, 'list_name' =>  'project_types', 'item_name' => 'Mystery Shopping - Phone Shops', 'status' => 1],
    		['id'   => 212, 'list_name' =>  'state', 'item_name' => 'FL', 'status' => 1],
    		['id'   => 213, 'list_name' =>  'state', 'item_name' => 'AS', 'status' => 1],
    		['id'   => 214, 'list_name' =>  'state', 'item_name' => 'CA', 'status' => 1],
    		['id'   => 215, 'list_name' =>  'state', 'item_name' => 'CN', 'status' => 1],
    		['id'   => 216, 'list_name' =>  'state', 'item_name' => 'CO', 'status' => 1],
    		['id'   => 217, 'list_name' =>  'state', 'item_name' => 'CT', 'status' => 1],
    		['id'   => 218, 'list_name' =>  'state', 'item_name' => 'DC', 'status' => 1],
    		['id'   => 219, 'list_name' =>  'state', 'item_name' => 'DE', 'status' => 1],
    		['id'   => 220, 'list_name' =>  'state', 'item_name' => 'FL', 'status' => 1],
    		['id'   => 221, 'list_name' =>  'state', 'item_name' => 'FM', 'status' => 1],
    		['id'   => 222, 'list_name' =>  'state', 'item_name' => 'GA', 'status' => 1],
    		['id'   => 223, 'list_name' =>  'state', 'item_name' => 'GU', 'status' => 1],
    		['id'   => 224, 'list_name' =>  'state', 'item_name' => 'HI', 'status' => 1],
    		['id'   => 225, 'list_name' =>  'state', 'item_name' => 'IA', 'status' => 1],
    		['id'   => 226, 'list_name' =>  'state', 'item_name' => 'ID', 'status' => 1],
    		['id'   => 227, 'list_name' =>  'state', 'item_name' => 'IL', 'status' => 1],
    		['id'   => 228, 'list_name' =>  'state', 'item_name' => 'IN', 'status' => 1],
    		['id'   => 229, 'list_name' =>  'state', 'item_name' => 'KS', 'status' => 1],
    		['id'   => 230, 'list_name' =>  'state', 'item_name' => 'KY', 'status' => 1],
    		['id'   => 231, 'list_name' =>  'state', 'item_name' => 'LA', 'status' => 1],
    		['id'   => 232, 'list_name' =>  'state', 'item_name' => 'MA', 'status' => 1],
    		['id'   => 233, 'list_name' =>  'state', 'item_name' => 'ME', 'status' => 1],
    		['id'   => 234, 'list_name' =>  'state', 'item_name' => 'MD', 'status' => 1],
    		['id'   => 235, 'list_name' =>  'state', 'item_name' => 'MI', 'status' => 1],
    		['id'   => 236, 'list_name' =>  'state', 'item_name' => 'MN', 'status' => 1],
    		['id'   => 237, 'list_name' =>  'state', 'item_name' => 'MO', 'status' => 1],
    		['id'   => 238, 'list_name' =>  'state', 'item_name' => 'MP', 'status' => 1],
    		['id'   => 239, 'list_name' =>  'state', 'item_name' => 'MS', 'status' => 1],
    		['id'   => 240, 'list_name' =>  'state', 'item_name' => 'MT', 'status' => 1],
    		['id'   => 241, 'list_name' =>  'state', 'item_name' => 'NC', 'status' => 1],
    		['id'   => 242, 'list_name' =>  'state', 'item_name' => 'ND', 'status' => 1],
    		['id'   => 243, 'list_name' =>  'state', 'item_name' => 'ND', 'status' => 1],
    		['id'   => 244, 'list_name' =>  'state', 'item_name' => 'NE', 'status' => 1],
    		['id'   => 245, 'list_name' =>  'state', 'item_name' => 'NH', 'status' => 1],
    		['id'   => 246, 'list_name' =>  'state', 'item_name' => 'NJ', 'status' => 1],
    		['id'   => 247, 'list_name' =>  'state', 'item_name' => 'NM', 'status' => 1],
    		['id'   => 248, 'list_name' =>  'state', 'item_name' => 'NV', 'status' => 1],
    		['id'   => 249, 'list_name' =>  'state', 'item_name' => 'NY', 'status' => 1],
    		['id'   => 250, 'list_name' =>  'state', 'item_name' => 'OH', 'status' => 1],
    		['id'   => 251, 'list_name' =>  'state', 'item_name' => 'OK', 'status' => 1],
    		['id'   => 252, 'list_name' =>  'state', 'item_name' => 'OR', 'status' => 1],
    		['id'   => 253, 'list_name' =>  'state', 'item_name' => 'PA', 'status' => 1],
    		['id'   => 254, 'list_name' =>  'state', 'item_name' => 'PR', 'status' => 1],
    		['id'   => 255, 'list_name' =>  'state', 'item_name' => 'PW', 'status' => 1],
    		['id'   => 256, 'list_name' =>  'state', 'item_name' => 'RI', 'status' => 1],
    		['id'   => 257, 'list_name' =>  'state', 'item_name' => 'SC', 'status' => 1],
    		['id'   => 258, 'list_name' =>  'state', 'item_name' => 'SD', 'status' => 1],
    		['id'   => 259, 'list_name' =>  'state', 'item_name' => 'TN', 'status' => 1],
    		['id'   => 260, 'list_name' =>  'state', 'item_name' => 'TX', 'status' => 1],
    		['id'   => 261, 'list_name' =>  'state', 'item_name' => 'UT', 'status' => 1],
    		['id'   => 262, 'list_name' =>  'state', 'item_name' => 'VA', 'status' => 1],
    		['id'   => 263, 'list_name' =>  'state', 'item_name' => 'VI', 'status' => 1],
    		['id'   => 264, 'list_name' =>  'state', 'item_name' => 'VT', 'status' => 1],
    		['id'   => 265, 'list_name' =>  'state', 'item_name' => 'WA', 'status' => 1],
    		['id'   => 266, 'list_name' =>  'state', 'item_name' => 'WI', 'status' => 1],
    		['id'   => 267, 'list_name' =>  'state', 'item_name' => 'WV', 'status' => 1],
    		['id'   => 268, 'list_name' =>  'state', 'item_name' => 'WY', 'status' => 1],
    		['id'   => 269, 'list_name' =>  'state', 'item_name' => 'AB', 'status' => 1],
    		['id'   => 270, 'list_name' =>  'state', 'item_name' => 'MB', 'status' => 1],
    		['id'   => 271, 'list_name' =>  'state', 'item_name' => 'NB', 'status' => 1],
    		['id'   => 272, 'list_name' =>  'state', 'item_name' => 'NL', 'status' => 1],
    		['id'   => 273, 'list_name' =>  'state', 'item_name' => 'NS', 'status' => 1],
    		['id'   => 274, 'list_name' =>  'state', 'item_name' => 'NT', 'status' => 1],
    		['id'   => 275, 'list_name' =>  'state', 'item_name' => 'NU', 'status' => 1],
    		['id'   => 276, 'list_name' =>  'state', 'item_name' => 'ON', 'status' => 1],
    		['id'   => 277, 'list_name' =>  'state', 'item_name' => 'PE', 'status' => 1],
    		['id'   => 278, 'list_name' =>  'state', 'item_name' => 'QC', 'status' => 1],
    		['id'   => 279, 'list_name' =>  'state', 'item_name' => 'SK', 'status' => 1],
    	]);
}
}
